sudo: required

services:
  - docker

before_install:
  - docker build -t kristijanklepac/dockerizereact -f Dockerfile.dev .

script:
  - docker run kristijanklepac/dockerizereact npm run test -- --coverage