sudo: required
language: python
python:
  - 2.7
  - 3.2
  - 3.5
services:
  - docker

before_install:
  - docker build -t kristijanklepac/dockerizereact -f Dockerfile.dev .

scripts:
  - docker run kristijanklepac/dockerizereact npm run test -- --coverage