language: ruby
sudo: required
services:
- docker

before_install:
- gem update bundler
- gem install rake
- docker build -t kristijanklepac/dockerizereact -f Dockerfile.dev .

scripts:
- docker run kristijanklepac/dockerizereact npm run test -- --coverage